config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :meisters, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'sessions' }
  root 'tests#index'

  resources :users, only: :create
  resources :sessions, only: :create

  get 'profile', to: 'profile#show'
  get 'contact_us', to: 'messages#new'

  resources :messages, only: :create
  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true
    end

    collection do
      get :table
    end

    member do
      post :start
    end
  end

  namespace :admin do
    resources :badges
    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[show index]
      end
    end
  end

  # GET /participations/101/result
  resources :participations, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/participation.rb
# frozen_string_literal: true

class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  validates :user, :test, presence: true

  before_validation :before_validation_set_first_question, on: :create

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    # чтобы нельзя было продолжать слать ответы после того как время вышло
    # принимаем последний выбранный ответ и переводим тест в completed
    unless completed?
      self.correct_questions += 1 if correct_answer?(answer_ids)
      self.current_question = next_question
      save!
    end
    self.current_question = nil if time_to_pass_over?
  end

  def current_question_counter
    test.questions.order(:id).where('id <= ?', current_question.id).size
  end

  def success?
    total_result >= 85
  end

  def total_result
    ((correct_questions.to_f / test.questions.size) * 100).round(2)
  end

  def progress
    (100 * current_question_counter) / test.questions.size
  end

  def time_to_pass_over?
    (Time.current - created_at) >= test.time_to_pass if test.time_to_pass
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    # есль пользователь не выбрал ни один чекбокс - ответ признается как неверный
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :text, presence: true

  def maximum_answers?
    answers.size >= 4
  end
end

app/controllers/participations_controller.rb
# frozen_string_literal: true

class ParticipationsController < ApplicationController
  before_action :find_participation, only: %i[show update result gist]
  before_action :set_test, only: %i[show update result]

  def show; end

  def result; end

  def gist
    result = GistQuestionService.new(@participation.current_question).call

    flash_options = if result.success?
                      current_user.gists.create(question: @participation.current_question,
                                                gist_hash: result.gist_hash,
                                                gist_url: result.gist_url)

                      { notice: t('.success', url: result.gist_url) }
                    else
                      { alert: t('.fail') }
    end

    redirect_to @participation, flash_options
  end

  def update
    @participation.accept!(params[:answer_ids])
    if @participation.completed?
      awards = BadgesRewardService.new(@participation).call

      if awards.present?
        current_user.badges << awards
        flash[:notice] = t('.new_awards', url: badges_url)
      end

      TestsMailer.completed_test(@participation).deliver_now
      redirect_to result_participation_path(@participation)
    else
      render :show
    end
  end

  private

  def find_participation
    @participation = Participation.find(params[:id])
  end

  def set_test
    @test = @participation.test
  end
end

app/views/participations/_linktests.html.erb
<%= link_to t('.all_tests'), tests_path, class: 'btn btn-secondary', id: :back_to_tests %>

app/views/participations/_progress_bar.html.erb
<div class="progress">
  <div class="progress-bar" id="progress-bar" data-progress="<%= @participation.progress %>" aria-valuemax="100">
    <%= @participation.progress %>%
  </div>
</div>

app/views/participations/_timer.html.erb
<% if @participation.test.time_to_pass %>

  <div class="user-timer" id="countdown" data-time="<%= @participation.test.time_to_pass %>"
                                         data-result_link="<%= result_participation_url(@participation) %>"
                                         data-test_created="<%= @participation.created_at.to_i %>" >
  </div>
<% end %>

app/views/participations/result.html.erb
<% color = @participation.success? ? "success" : "fail" %>
<div class="container">
  <h1><%= t('.header', title: @participation.test.title) %></h1>
  <div class="text-center">  
    <% if @participation.success? %>
      <h3><%= t('.congratulations') %></h2>
    <% else %>
      <h3><%= t('.condolences') %></h2>
    <% end %>
    <h3 class="<%= color %>"><%= t('.result') %> <%= @participation.total_result %>%.</h3>
    <%= render "linktests" %>
  </div>

</div>

app/views/participations/show.html.erb
<div class="container">
  <h1><%= t('.participation', test_title: @participation.test.title) %></h1>
  
  <div>
     <%= render 'progress_bar' %>
  </div>
  <div class="status text-secondary">
    <%= t('.question', current_number: @participation.current_question_counter) %>
    <%= t('.out_of', all_counter: @participation.test.questions.count) %>
  </div>
  <div>
    <h2 class="text-center">
      <%= render 'timer' %>
    </h2>
  </div>
  
  <p><b> <%= @participation.current_question.text %></b></p>
  <div class="form-group">
    <%= form_with url: participation_path(@participation), local: true, method: :put do |f| %>
      <%= f.collection_check_boxes :answer_ids, @participation.current_question.answers, :id, :text,  include_hidden: false do |b| %>
        <div class="form-check">
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
      <%= link_to t('.gist_question'), gist_participation_path(@participation), method: :post, class: 'btn btn-warning' %>
      <%= f.submit t('.next'), class: 'btn btn-primary', id: 'btnnext' %>
    </div>
  <% end %>
  <%= render "linktests" %>
</div>