config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :meisters, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'sessions' }
  root 'tests#index'

  resources :users, only: :create
  resources :sessions, only: :create

  get 'profile', to: 'profile#show'
  get 'contact_us', to: 'messages#new'

  resources :messages, only: :create
  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true
    end

    collection do
      get :table
    end

    member do
      post :start
    end
  end

  namespace :admin do
    resources :badges
    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[show index]
      end
    end
  end

  # GET /participations/101/result
  resources :participations, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <div class="alert alert-error">
      <%= t('.header', count: resource.errors.count) %>
    </div>
    <ul>
        <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
   <%= content_tag :div, sanitize(message, attributes: %w(href target)).html_safe, class: [:alert, alert_for(type)]%>
<% end %>

app/views/shared/_footer.html.erb
<div class="container"> 
    <div class="row text-center">
      <div class="col">
        <%= link_to t('.feedback'), contact_us_path %>
      </div>
    </div>
    <div class="row text-center">
      <div class="col">
        <%= current_year %> <%= t('.copyright') %> <%= github_url('ellerden', 'test-guru') %>
      </div>
    </div>
    <div class="row text-center">
      <div class="col">
        <%= t('.about_project') %> <a target="_blank" href="https://thinknetica.com"> Thinknetica </a> 
      </div>
    </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestMeister', root_path, class: 'navbar-brand' %>
  <% if user_signed_in? && current_user.admin_rights?%>
  <%= link_to t('.admin_panel_title'), admin_tests_path, class: 'navbar-brand' %>
  <% end %>
  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('.welcome') %> <b><%= current_user.first_name %></b>!
      <%= link_to t('.profile'), profile_path %>
      <%= link_to t('.badges'), badges_path %>
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.login'), new_user_session_path %>
      <%= link_to t('.signup'), new_user_registration_path %>
    <% end %>
  </span> 
</nav>