config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :meisters, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'sessions' }
  root 'tests#index'

  resources :users, only: :create
  resources :sessions, only: :create

  get 'profile', to: 'profile#show'
  get 'contact_us', to: 'messages#new'

  resources :messages, only: :create
  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true
    end

    collection do
      get :table
    end

    member do
      post :start
    end
  end

  namespace :admin do
    resources :badges
    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[show index]
      end
    end
  end

  # GET /participations/101/result
  resources :participations, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :text, presence: true
  validate :validate_answers_length, on: :create

  def maximum_capacity?
    question.answers.size > 4
  end

  private

  def validate_answers_length
    errors.add(:base, :max_answers) if maximum_capacity?
  end
end

app/controllers/admin/answers_controller.rb
# frozen_string_literal: true

class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  # /answers/id
  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.build(answer_params)
    if @answer.save
      redirect_to admin_question_path(@answer.question), notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question), notice: t('.success')
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:text, :correct)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
  def answer_question_text(answer)
    content_tag(:h2, t('.question', question_text: answer.question.text))
  end
end

app/views/admin/answers/_answer.html.erb
<div class="container">
  <tr>
    <td style="text-align: center">
      <%= form_with(model: [:admin, answer], local: true) do |f| %>
        <div class="form-check">
          <%= f.label :correct, class: "form-check-label" do %>
            <%= f.check_box :correct, class: "form-check-input" %>
            <%= answer.text %>
          <% end %>
        </div>
      <% end %>
    </td>
    <td class="text-center"> 
      <%= link_to t('.edit'), edit_admin_answer_path(answer) %> 
    </td>
    <td class="text-center"> 
      <%= link_to t('.delete'), admin_answer_path(answer), method: :delete %> 
    </td>
  </tr>
</div>

app/views/admin/answers/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col col-6">
      <%= show_header(@answer) %>
      <%= answer_question_text(@answer) %>
      <%= render 'shared/errors', resource: @answer %>
    </div>

    
  </div>
  <%= form_with(model: [:admin, @question, @answer], local: true) do |f| %>
    <div class="row">
      <div class="col col-6">
        <div class="form-group">
          <p>
            <%= f.label :text %>
            <%= f.text_area :text, id: :text, rows: 7, cols: 60, placeholder: true  %>
          </p>
          <p>
            <%= f.label :correct %>
            <%= f.check_box :correct, id: :correct %>
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col col-12">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to t('.back'), admin_question_path(@answer.question), class: "nav-link" %> 
      </div>
    </div>
  <% end %>
</div>

app/views/admin/answers/edit.html.erb
<%= render 'form' %>