config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :meisters, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'sessions' }
  root 'tests#index'

  resources :users, only: :create
  resources :sessions, only: :create

  get 'profile', to: 'profile#show'
  get 'contact_us', to: 'messages#new'

  resources :messages, only: :create
  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true
    end

    collection do
      get :table
    end

    member do
      post :start
    end
  end

  namespace :admin do
    resources :badges
    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: %i[show index]
      end
    end
  end

  # GET /participations/101/result
  resources :participations, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :text, presence: true

  def maximum_answers?
    answers.size >= 4
  end
end

app/controllers/admin/questions_controller.rb
# frozen_string_literal: true

class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[destroy show edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  # /tests/:test_id/questions/new(.:format)
  def new
    @question = @test.questions.build
  end

  def create
    @question = @test.questions.build(question_params)
    if @question.save
      redirect_to admin_test_path(@test), notice: t('.success')
    else
      render :new
    end
  end

  # /questions/:id(.:format)
  def destroy
    @question.destroy
    redirect_to admin_test_path(Test.find(@question.test_id)), notice: t('.success')
  end

  # /questions/:id(.:format)
  def show; end

  # /questions/:id(.:format)/edit
  def edit; end

  # апдейтит только текст вопроса, чтобы апдейтить и привязку к конкретному тесту,
  # нужно менять пермиты в question_params
  def update
    if @question.update(question_params)
      redirect_to admin_test_path(Test.find(@question.test_id)), notice: t('.success')
    else
      render :new
    end
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:text)
  end

  def rescue_with_question_not_found
    redirect_to admin_tests_path, alert: t('.not_found')
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    content_tag(:h1, question.persisted? ? t('.edit_question', title: question.test.title) : t('.new_question', title: question.test.title))
  end
end

app/views/admin/questions/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col col-6">
      <%= question_header(@question) %>
    </div>
  </div>
      <%= form_with(model: [:admin, @test, @question], local: true) do |f| %>
        <div class="row">
          <div class="col col-6">
            <div class="form-group">
                <%= f.label :text %>
                <%= f.text_field :text, placeholder: true, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.submit class: "btn btn-primary" %>
            <%= link_to t('.back'), admin_test_path(@question.test), class: "nav-link" %>
          </div>
        </div> 
      <% end %>
  </div>
</div>

app/views/admin/questions/_question.html.erb
<%= question.text %>
<div>
  <p>
    <%= link_to t('.show_answers'), admin_question_path(question) %>
    <%= link_to t('.edit'), edit_admin_question_path(question) %>
    <%= link_to t('.delete'), admin_question_path(question), method: :delete %>
  </p>
</div>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

app/views/admin/questions/index.html.erb
<% if @questions.present? %>
    <h2><%= t('.header') %></h2>
    <%= render @questions%>
<% end %>

app/views/admin/questions/new.html.erb
<%# Форма для создания вопроса %>
<%= render "form" %>

app/views/admin/questions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col col-12">
      <h1> <%= t('.header', title: @question.test.title) %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col col-12">
      <h2> <%= @question.text %> </h2>
      <p class="text-muted"><%= t('.max_answers_info') %></p>
    </div>
  </div>
  <div class="row">
    <div class="col col-12">
      <%= render @question.answers %>
    </div>
  </div>
  <div class="row">
    <div class="col col-12">
      <%= link_to t('.new_answer'), new_admin_question_answer_path(@question), class: "btn btn-primary answer-btn", data: { maximum: @question.maximum_answers? } %>
      <%= link_to t('.back'), admin_test_path(@question.test), class: "nav-link" %> 
    </div>
  </div>
</div>